name: PR Merge Readiness Check

on:
  pull_request:
    types:
      - opened      # PR 首次创建时
      - synchronize # PR 有新的提交时（内容更新）
      - reopened    # PR 从关闭状态重新打开时
      - edited      # PR 描述/标题被编辑时（内容更新）
      - labeled     # PR 添加标签时
      - unlabeled   # PR 移除标签时

permissions:
  pull-requests: read # 只需要读取 PR 的 body 和 labels

jobs:
  check-merge-readiness:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR for merge blockers
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            const prLabels = context.payload.pull_request.labels;
            const prNumber = context.payload.pull_request.number;

            let fail = false;
            let errorMessage = '';

            core.info(`Checking Pull Request #${prNumber} for merge blockers...`);
            core.info(`PR Body Preview:\n---\n${prBody ? prBody.substring(0, 500) + (prBody.length > 500 ? '...' : '') : '[Empty]'}\n---`);
            core.info(`PR Labels: ${JSON.stringify(prLabels.map(label => label.name))}`);

            // 检查条件 1: PR 内容有独立一行前后无空格的 !do-not-merge-yet 标记
            // 正则表达式解释：
            // ^       : 匹配行的开始 (由于 'm' (multiline) 标志)
            // \s*     : 匹配零个或多个空格字符
            // !do-not-merge-yet : 匹配字面字符串
            // \s*     : 匹配零个或多个空格字符
            // $       : 匹配行的结束 (由于 'm' (multiline) 标志)
            // m       : 多行标志，使 ^ 和 $ 匹配每一行的开始/结束，而不是整个字符串的开始/结束
            if (prBody && /^\s*!do-not-merge-yet\s*$/m.test(prBody)) {
                fail = true;
                const msg = "Error: PR body contains '!do-not-merge-yet' as a standalone line. Please remove this marker before merging.";
                errorMessage += msg + '\n';
                core.error(msg); // 错误日志，会在 Actions 运行中显示为红色
            }

            // 检查条件 2: PR 有 'do not merge' 标签
            const hasDoNotMergeLabel = prLabels.some(label => label.name.toLowerCase() === 'do not merge');
            if (hasDoNotMergeLabel) {
                fail = true;
                const msg = "Error: PR has the 'do not merge' label. Please remove this label before merging.";
                errorMessage += msg + '\n';
                core.error(msg); // 错误日志
            }

            if (fail) {
                // 如果任何一个条件满足，则使 Actions 任务失败
                core.setFailed(errorMessage);
            } else {
                core.info("PR passed all merge readiness checks. Good to go!");
            }
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}